### ISSUE TITLE
Failed to install add-on

### ISSUE THREAD

**Issue by fastovenko** [tsujamin/hass-addons#12] opened 2021-06-23 07:03 UTC
I added add-on with Supervisor.
When I click a button Install, I get the error:
"The command '/bin/ash -o pipefail -c /install.sh $BUILD_ARCH $TAILSCALE_VERSION' returned a non-zero code: 1"

What should I do to install it?

HA core v.2021.6.5
Add-on v.1.8.7.0

**Comment by tsujamin** [comment] 2021-06-25 11:09
Sorry to hear you're having an issue. Some quick questions/requests so I can try debug the issue:

  * Could you check if there was any additional logging/output generated when you installed the plugin? Check your logs under Supervisor->System as you attempt to reinstall, or run `ha supervisor logs` via one of the SSH addons
  * Could you confirm you can reach https://pkgs.tailscale.com/stable/ from your browser?
  * Do you know if your internet connection supports IPv6? There's another issue where I think IPv6 might be the cause, maybe try https://test-ipv6.com/ to confirm

I just pushed the new tailscale version so make sure to reload your addon repositories before trying again :)

**Comment by Vansmak** [comment] 2021-07-12 05:49
same issue for me but. it installs fine on my hassos or my pi running hassos.  but trying to install in on my other ha which is a supervised install ( not hass io) I get the same error as the op

**Comment by tsujamin** [comment] 2021-07-14 12:24
Sorry my email notifications were whack so I missed this, any chance you can follow the steps above and report back?

**Comment by Vansmak** [comment] 2021-07-14 22:57
it was a bad ha install on my end.

**Comment by tsujamin** [comment] 2021-07-14 23:13
Ah awesome, let me know if you have any more issues 😁

On 15 Jul 2021, at 8:57 am, Vansmak ***@***.***> wrote:

﻿

it was a bad ha install on my end.

**Comment by sheminasalam** [comment] 2021-07-30 13:00
This has happened to me also. Any tips on solving this?

**Comment by Vansmak** [comment] 2021-07-30 14:35
for other unrelated reasons i had re-install my ha and after i did then this error went away.  that seems like a drastic thing to do for one add-on but I suspect supervisor didn't install properly.

**Comment by sheminasalam** [comment] 2021-07-30 14:42
All my other addons are working without any issues so I dont think the problem could be with the supervisor. There might be some other thing that is causing the issue.

**Comment by Vansmak** [comment] 2021-07-30 15:19
I'm just telling you what happened in my case. I'm not even using this add-on. wireguard is all i need. no fuss

**Comment by tsujamin** [comment] 2021-07-31 09:24
@sheminasalam Can you confirm if this is the same kind of issue as in #11? If so I might try and move the conversation over there and close this

**Comment by sheminasalam** [comment] 2021-07-31 11:24
yes that is the issue.

**Comment by tsujamin** [comment] 2021-08-13 08:44
Alright I'll close this to focus conversation over there sorry

**Closed by tsujamin** 2021-08-13 08:44 UTC
